# Generated by Django 5.0.6 on 2025-07-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Büyük Başlık')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Alt Başlık')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Slider Görseli')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Buton Yazısı')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Buton Linki')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['order'],
            },
        ),
    ]
