# Generated by Django 5.0.6 on 2025-07-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_color_size_texture_usagearea_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='colors/'),
        ),
        migrations.AddField(
            model_name='size',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sizes/'),
        ),
        migrations.AddField(
            model_name='texture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='textures/'),
        ),
        migrations.AddField(
            model_name='usagearea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='usage_areas/'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usagearea',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
