# Generated by Django 5.0.6 on 2025-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_color_image_size_image_texture_image_usagearea_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='image',
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.PositiveIntegerField(verbose_name='En'),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Boy'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Doku'),
        ),
        migrations.AlterField(
            model_name='usagearea',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kullanım ALanı'),
        ),
    ]
